---
- name: "Stage 4: Upload image to BCM, configure PXE"
  hosts: localhost
  gather_facts: true
  vars:
    e2e_dir: "{{ lookup('env', 'E2E_DIR') | default(playbook_dir + '/..', true) }}"
    build_dir: "{{ e2e_dir }}/build"
    dist_dir: "{{ e2e_dir }}/dist"
  roles:
    - deploy_dd
